services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - 3001:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-nw-networks

  db:
    image: mysql:8.0-debian
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes: # monte un volume pour faire persiter les données MySQL
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]  # Vérifie si MySQL est accessible
      interval: 10s  # lance le test toute les 10s
      timeout: 5s    # Timeout après 5 secondes
      retries: 3     # fait le test 3 fois
    networks:
      - app-nw-networks

  front:
    build:
      context: ../Front_Club_Sportif
      dockerfile: dockerfile
    ports: # à droite port de l'hôte et à gauche le port du conteneur 
      - 80:80
    depends_on:
      - db
    networks:
      - app-nw-networks
volumes:
  mysql-data:

networks:
  app-nw-networks: